// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.admingol.domain;

import com.raze.admingol.catalog.ConceptoCobro;
import com.raze.admingol.catalog.ConceptoCobroDataOnDemand;
import com.raze.admingol.catalog.StatusCargoAbonoDataOnDemand;
import com.raze.admingol.domain.AbonoDataOnDemand;
import com.raze.admingol.domain.Cargo;
import com.raze.admingol.domain.CargoDataOnDemand;
import com.raze.admingol.domain.Equipo;
import com.raze.admingol.domain.EquipoDataOnDemand;
import com.raze.admingol.domain.Torneo;
import com.raze.admingol.domain.TorneoDataOnDemand;
import com.raze.admingol.domain.UsuarioDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CargoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CargoDataOnDemand: @Component;
    
    private Random CargoDataOnDemand.rnd = new SecureRandom();
    
    private List<Cargo> CargoDataOnDemand.data;
    
    @Autowired
    AbonoDataOnDemand CargoDataOnDemand.abonoDataOnDemand;
    
    @Autowired
    ConceptoCobroDataOnDemand CargoDataOnDemand.conceptoCobroDataOnDemand;
    
    @Autowired
    EquipoDataOnDemand CargoDataOnDemand.equipoDataOnDemand;
    
    @Autowired
    StatusCargoAbonoDataOnDemand CargoDataOnDemand.statusCargoAbonoDataOnDemand;
    
    @Autowired
    TorneoDataOnDemand CargoDataOnDemand.torneoDataOnDemand;
    
    @Autowired
    UsuarioDataOnDemand CargoDataOnDemand.usuarioDataOnDemand;
    
    public Cargo CargoDataOnDemand.getNewTransientCargo(int index) {
        Cargo obj = new Cargo();
        setConceptoCobro(obj, index);
        setEquipo(obj, index);
        setFechaCreacion(obj, index);
        setFechaModificacion(obj, index);
        setMonto(obj, index);
        setObservaciones(obj, index);
        setTorneo(obj, index);
        return obj;
    }
    
    public void CargoDataOnDemand.setConceptoCobro(Cargo obj, int index) {
        ConceptoCobro conceptoCobro = conceptoCobroDataOnDemand.getRandomConceptoCobro();
        obj.setConceptoCobro(conceptoCobro);
    }
    
    public void CargoDataOnDemand.setEquipo(Cargo obj, int index) {
        Equipo equipo = equipoDataOnDemand.getRandomEquipo();
        obj.setEquipo(equipo);
    }
    
    public void CargoDataOnDemand.setFechaCreacion(Cargo obj, int index) {
        Date fechaCreacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaCreacion(fechaCreacion);
    }
    
    public void CargoDataOnDemand.setFechaModificacion(Cargo obj, int index) {
        Date fechaModificacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaModificacion(fechaModificacion);
    }
    
    public void CargoDataOnDemand.setMonto(Cargo obj, int index) {
        double monto = new Integer(index).doubleValue();
        obj.setMonto(monto);
    }
    
    public void CargoDataOnDemand.setObservaciones(Cargo obj, int index) {
        String observaciones = "observaciones_" + index;
        obj.setObservaciones(observaciones);
    }
    
    public void CargoDataOnDemand.setTorneo(Cargo obj, int index) {
        Torneo torneo = torneoDataOnDemand.getRandomTorneo();
        obj.setTorneo(torneo);
    }
    
    public Cargo CargoDataOnDemand.getSpecificCargo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Cargo obj = data.get(index);
        Long id = obj.getId();
        return Cargo.findCargo(id);
    }
    
    public Cargo CargoDataOnDemand.getRandomCargo() {
        init();
        Cargo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Cargo.findCargo(id);
    }
    
    public boolean CargoDataOnDemand.modifyCargo(Cargo obj) {
        return false;
    }
    
    public void CargoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Cargo.findCargoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Cargo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Cargo>();
        for (int i = 0; i < 10; i++) {
            Cargo obj = getNewTransientCargo(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
