// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.admingol.domain;

import com.raze.admingol.catalog.PosicionDataOnDemand;
import com.raze.admingol.catalog.StatusEquipoJugadorDataOnDemand;
import com.raze.admingol.domain.Equipo;
import com.raze.admingol.domain.EquipoDataOnDemand;
import com.raze.admingol.domain.Jugador;
import com.raze.admingol.domain.JugadorDataOnDemand;
import com.raze.admingol.domain.UsuarioDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect JugadorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JugadorDataOnDemand: @Component;
    
    private Random JugadorDataOnDemand.rnd = new SecureRandom();
    
    private List<Jugador> JugadorDataOnDemand.data;
    
    @Autowired
    EquipoDataOnDemand JugadorDataOnDemand.equipoDataOnDemand;
    
    @Autowired
    PosicionDataOnDemand JugadorDataOnDemand.posicionDataOnDemand;
    
    @Autowired
    StatusEquipoJugadorDataOnDemand JugadorDataOnDemand.statusEquipoJugadorDataOnDemand;
    
    @Autowired
    UsuarioDataOnDemand JugadorDataOnDemand.usuarioDataOnDemand;
    
    public Jugador JugadorDataOnDemand.getNewTransientJugador(int index) {
        Jugador obj = new Jugador();
        setActivo(obj, index);
        setApellidoMaterno(obj, index);
        setApellidoPaterno(obj, index);
        setCorreoE(obj, index);
        setDomicilio(obj, index);
        setEquipo(obj, index);
        setEsDelegado(obj, index);
        setFechaCreacion(obj, index);
        setFechaModificacion(obj, index);
        setFechaNacimiento(obj, index);
        setFoto(obj, index);
        setNombre(obj, index);
        setTelefono(obj, index);
        return obj;
    }
    
    public void JugadorDataOnDemand.setActivo(Jugador obj, int index) {
        Boolean activo = Boolean.TRUE;
        obj.setActivo(activo);
    }
    
    public void JugadorDataOnDemand.setApellidoMaterno(Jugador obj, int index) {
        String apellidoMaterno = "apellidoMaterno_" + index;
        obj.setApellidoMaterno(apellidoMaterno);
    }
    
    public void JugadorDataOnDemand.setApellidoPaterno(Jugador obj, int index) {
        String apellidoPaterno = "apellidoPaterno_" + index;
        obj.setApellidoPaterno(apellidoPaterno);
    }
    
    public void JugadorDataOnDemand.setCorreoE(Jugador obj, int index) {
        String correoE = "correoE_" + index;
        obj.setCorreoE(correoE);
    }
    
    public void JugadorDataOnDemand.setDomicilio(Jugador obj, int index) {
        String domicilio = "domicilio_" + index;
        obj.setDomicilio(domicilio);
    }
    
    public void JugadorDataOnDemand.setEquipo(Jugador obj, int index) {
        Equipo equipo = equipoDataOnDemand.getRandomEquipo();
        obj.setEquipo(equipo);
    }
    
    public void JugadorDataOnDemand.setEsDelegado(Jugador obj, int index) {
        Boolean esDelegado = Boolean.TRUE;
        obj.setEsDelegado(esDelegado);
    }
    
    public void JugadorDataOnDemand.setFechaCreacion(Jugador obj, int index) {
        Date fechaCreacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaCreacion(fechaCreacion);
    }
    
    public void JugadorDataOnDemand.setFechaModificacion(Jugador obj, int index) {
        Date fechaModificacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaModificacion(fechaModificacion);
    }
    
    public void JugadorDataOnDemand.setFechaNacimiento(Jugador obj, int index) {
        Date fechaNacimiento = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaNacimiento(fechaNacimiento);
    }
    
    public void JugadorDataOnDemand.setFoto(Jugador obj, int index) {
        byte[] foto = String.valueOf(index).getBytes();
        obj.setFoto(foto);
    }
    
    public void JugadorDataOnDemand.setNombre(Jugador obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void JugadorDataOnDemand.setTelefono(Jugador obj, int index) {
        String telefono = "telefono_" + index;
        obj.setTelefono(telefono);
    }
    
    public Jugador JugadorDataOnDemand.getSpecificJugador(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Jugador obj = data.get(index);
        Long id = obj.getId();
        return Jugador.findJugador(id);
    }
    
    public Jugador JugadorDataOnDemand.getRandomJugador() {
        init();
        Jugador obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Jugador.findJugador(id);
    }
    
    public boolean JugadorDataOnDemand.modifyJugador(Jugador obj) {
        return false;
    }
    
    public void JugadorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Jugador.findJugadorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Jugador' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Jugador>();
        for (int i = 0; i < 10; i++) {
            Jugador obj = getNewTransientJugador(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
