// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.admingol.domain;

import com.raze.admingol.catalog.StatusPartido;
import com.raze.admingol.catalog.StatusPartidoDataOnDemand;
import com.raze.admingol.catalog.TipoPartidoDataOnDemand;
import com.raze.admingol.domain.Cancha;
import com.raze.admingol.domain.CanchaDataOnDemand;
import com.raze.admingol.domain.EquipoDataOnDemand;
import com.raze.admingol.domain.HorarioDataOnDemand;
import com.raze.admingol.domain.Partido;
import com.raze.admingol.domain.PartidoDataOnDemand;
import com.raze.admingol.domain.TorneoDataOnDemand;
import com.raze.admingol.domain.UsuarioDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PartidoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PartidoDataOnDemand: @Component;
    
    private Random PartidoDataOnDemand.rnd = new SecureRandom();
    
    private List<Partido> PartidoDataOnDemand.data;
    
    @Autowired
    CanchaDataOnDemand PartidoDataOnDemand.canchaDataOnDemand;
    
    @Autowired
    EquipoDataOnDemand PartidoDataOnDemand.equipoDataOnDemand;
    
    @Autowired
    HorarioDataOnDemand PartidoDataOnDemand.horarioDataOnDemand;
    
    @Autowired
    StatusPartidoDataOnDemand PartidoDataOnDemand.statusPartidoDataOnDemand;
    
    @Autowired
    TipoPartidoDataOnDemand PartidoDataOnDemand.tipoPartidoDataOnDemand;
    
    @Autowired
    TorneoDataOnDemand PartidoDataOnDemand.torneoDataOnDemand;
    
    @Autowired
    UsuarioDataOnDemand PartidoDataOnDemand.usuarioDataOnDemand;
    
    public Partido PartidoDataOnDemand.getNewTransientPartido(int index) {
        Partido obj = new Partido();
        setCancha(obj, index);
        setFechaCreacion(obj, index);
        setFechaJuego(obj, index);
        setFechaModificacion(obj, index);
        setStatus(obj, index);
        return obj;
    }
    
    public void PartidoDataOnDemand.setCancha(Partido obj, int index) {
        Cancha cancha = canchaDataOnDemand.getRandomCancha();
        obj.setCancha(cancha);
    }
    
    public void PartidoDataOnDemand.setFechaCreacion(Partido obj, int index) {
        Date fechaCreacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaCreacion(fechaCreacion);
    }
    
    public void PartidoDataOnDemand.setFechaJuego(Partido obj, int index) {
        Date fechaJuego = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaJuego(fechaJuego);
    }
    
    public void PartidoDataOnDemand.setFechaModificacion(Partido obj, int index) {
        Date fechaModificacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaModificacion(fechaModificacion);
    }
    
    public void PartidoDataOnDemand.setStatus(Partido obj, int index) {
        StatusPartido status = statusPartidoDataOnDemand.getRandomStatusPartido();
        obj.setStatus(status);
    }
    
    public Partido PartidoDataOnDemand.getSpecificPartido(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Partido obj = data.get(index);
        Long id = obj.getId();
        return Partido.findPartido(id);
    }
    
    public Partido PartidoDataOnDemand.getRandomPartido() {
        init();
        Partido obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Partido.findPartido(id);
    }
    
    public boolean PartidoDataOnDemand.modifyPartido(Partido obj) {
        return false;
    }
    
    public void PartidoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Partido.findPartidoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Partido' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Partido>();
        for (int i = 0; i < 10; i++) {
            Partido obj = getNewTransientPartido(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
