// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.admingol.domain;

import com.raze.admingol.domain.TorneoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TorneoIntegrationTest_Roo_Configurable {
    
    declare @type: TorneoIntegrationTest: @Configurable;
    
}
